### ISSUE TITLE
Changing the 'weighing' parameter of the single_link redundancy to 'time' instead of distance does not work

### ISSUE THREAD

**Issue by LiekeMeijer** [Deltares/ra2ce#439] opened 2024-05-21 09:23 UTC
### Ra2ce version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of Ra2ce in `master` [here](https://github.com/Deltares/ra2ce).

### Reproducible example

I tested some functionality and tried to perform a single link redundancy with 'time' as the weighing parameter of the single link redundancy function. While RA2CE does not crash, the output is exactly the same as when using 'distance' as the weighing parameter. I am not sure if 'time' is still a functionality that we want to support, but probably? I have a Jupyter notebook and an analysis ini to reproduce upon request. I also do not see the 'time' option worked out in the code. If we do not support this anymore, we should update the documentation. 

From @Carsopre:
I can confirm this is a bug. It can be reproduced using the example in `tests/test_data/simple_inputs`:

```python
_case_dir = Path("tests", "test_data", "simple_inputs")
_network_config_data = NetworkConfigDataReader().read_file(_case_dir.joinpath("network.ini"))
_analyses_config_data = AnalysisConfigDataReader().read_file(_case_dir.joinpath("analysis.ini"))

# Modify the Analysis config data to weigh by `time`
_analyses_config_data[0].weighing = WeighingEnum.TIME

# Run analysis
Ra2ceHandler.run_with_config_data(_network_config_data, _analyses_config_data)
```

### Current behaviour

Setting the weighing parameter to 'time' does not provide any other output than specifying 'distance' in the analysis ini for single link redundancy.  

### Desired behaviour

Using time as weight.

**Comment by Carsopre** [comment] 2024-05-31 08:37
I can confirm this is a bug. It can be reproduced using the example in `tests/test_data/simple_inputs`:

```python
_case_dir = Path("tests", "test_data", "simple_inputs")
_network_config_data = NetworkConfigDataReader().read_file(_case_dir.joinpath("network.ini"))
_analyses_config_data = AnalysisConfigDataReader().read_file(_case_dir.joinpath("analysis.ini"))

# Modify the Analysis config data to weigh by `time`
_analyses_config_data[0].weighing = WeighingEnum.TIME

# Run analysis
Ra2ceHandler.run_with_config_data(_network_config_data, _analyses_config_data)
```

**Comment by ArdtK** [comment] 2024-05-31 12:38
@LiekeMeijer it seems value `distance` is previously not considered a valid value, looking at WeighingEnum. Besides, no calculator is available, only for `time` and `length`.

**Comment by ArdtK** [comment] 2024-05-31 13:32
@LiekeMeijer it seems the notebook analysis crashes once `time` is chosen as weighing as some edges lack the attribute `time`.
This will lead to a crash of the analysis in `single_link_redundancy` on line 83.
Should we investigate this further?

**Comment by LiekeMeijer** [comment] 2024-05-31 14:14
@mjevanmarle Is the time function still something that we want to support? I think we have not used this a lot over the past time but this may also be the explanation as to why it is not working at the moment.

**Comment by ArdtK** [comment] 2024-06-06 07:56
Discussed: both `time` and `distance` should work. In case `time` is missing `avg_speed` should be used.

**Comment by ArdtK** [comment] 2024-06-11 12:37
This is a duplicate of #433 and can be closed if that issue is closed. Linking it to the same PR for that reason.

**Closed** 2024-06-12 19:29 UTC
Labels: bug, documentation, enhancement
